# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: migupere <migupere@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/10/28 10:31:06 by pevieira          #+#    #+#              #
#    Updated: 2024/11/04 16:12:21 by migupere         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

# OUT = cub3d

# SRC = src/main.c

# OBJS = ${SRC:.c=.o}

# CC = gcc
# RM = rm -f
# CFLAGS = -Wall -Wextra -Werror -g
# INCLUDE = -I include
# MAKE = make -C
# LIBFT_PATH = libft
# MLX_PATH = mlx
# LIBFT = -L ${LIBFT_PATH} -lft
# MLX	= -L ${MLX_PATH} -lmlx -Ilmlx -lXext -lX11 -lm

# .c.o:
# 		${CC} ${CFLAGS} ${INCLUDE} -c $< -o ${<:.c=.o}

# $(OUT): ${OBJS}
# 		${MAKE} ${LIBFT_PATH}
# 		${CC} ${OBJS} ${LIBFT} -o ${OUT}

# all:	${OUT}

# clean:
# 		${MAKE} ${LIBFT_PATH} clean
# 		${RM} ${OBJS}

# fclean: clean
# 		${MAKE} ${LIBFT_PATH} fclean
# 		${RM} ${OUT}

# re: fclean all

# .PHONY: all clean fclean re


# FALTA : 
#.c.o:
#		${CC} ${CFLAGS} ${INCLUDE} -c $< -o ${<:.c=.o}

#$(OUT): ${OBJS}
#		${MAKE} ${LIBFT_PATH}
#		${MAKE} ${MLX_PATH}
#		${CC} ${OBJS} ${LIBFT} ${MLX} -o ${OUT}

#all:	${OUT}
#
#clean:
#		${MAKE} ${LIBFT_PATH} clean
#		${MAKE} ${MLX_PATH} clean
#		${RM} ${OBJS}

#fclean: clean
#		${MAKE} ${LIBFT_PATH} fclean
#		${RM} ${OUT}
